add_newline = false
format = """
[â•­â”€â”€â”€â”€](bold)$username$hostname$status$shell$git_branch$git_status$memory_usage$cmd_duration$battery â”€â”€â”€>>
[â”‚](bold)$directory
[â•°â”€](bold) $character """
[character]
error_symbol = "[âœ–](bold red)"
[cmd_duration]
show_milliseconds = true
format = "took [$duration](bold yellow) "
disabled = false
show_notifications = true
[memory_usage]
format = "$symbol [${ram_pct}](bold green) "
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"
[python]
format = "[$symbol$version]($style) "
style = "bold green"
[directory]
truncation_length = 10
truncation_symbol = "~/"
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "cyan bold"
[username]
style_user = "yellow bold"
style_root = "yellow bold"
format = " [$user]($style) "
disabled = false
show_always = true
[time]
disabled = false
format = ' $time ($style) '
[hostname]
ssh_only = false
format = 'on [$hostname](bold red) '
trim_at = "."
disabled = false
[status]
style = "red"
symbol = "ğŸ’¥ "
format = '$symbol$status($style) '
disabled = false
[git_branch]
format = "[ $symbol ](purple)[$branch]($style)"
style = "bold purple"
symbol = "î‚ "
[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
[[battery.display]]
threshold = 15
style = "bold red"
[[battery.display]]
threshold = 50
style = "bold yellow"
[[battery.display]]
threshold = 80
style = "bold green"
